version: 2.1

orbs:
  node: circleci/node@5.0.3
            
jobs:
  build:
    docker: 
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - node/install-packages
      - run:
          command: |
            npm run build
  test:
    docker: 
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - node/install-packages
      - run:
          command: |
            npm run test-ci-reporting
  lint:
    docker: 
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - node/install-packages
      - run:
          command: |
            npm run lint
            
workflows:
  build_test_deploy:
      jobs:
        - build
        - lint
        - test     

# VS Code Extension Version: 1.0.2